name: Build And Test (Angular)
description: Build angular dist folder
inputs:
  publish-profile:
    description: 'Publish Profile'
    required: true
  publish-angular:
    description: 'Angular Publish Type'
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    - name: Install dependencies
      run: |
        cd ./angular
        yarn
      shell: bash

    - name: Build dist
      run: |
        cd ./angular
        npm run ${{ inputs.publish-angular }}
      shell: bash
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Publish .Net
      run: |
        cd ./aspnet-core/src/GMS.Web.Host
        dotnet publish GMS.Web.Host.csproj /p:PublishProfile=.\Properties\PublishProfiles\${{ inputs.publish-profile }}.pubxml -c Release
      shell: bash
    - name: Upload Publish Folder
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: aspnet-core/src/GMS.Web.Host/bin/Release/net7.0/publish

