name: "Build, Test And Deploy To Staging"

on: 
  push:
    branches:
    - dev
    paths:
    - 'angular/src/**'
    - 'aspnet-core/src/**'
  workflow_dispatch:

jobs:
  check-is-valid-branch:
    name: Check Is Valid Branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/check-is-valid-branch
      with:
        branch_name: dev
        
  build-and-test-backend:
    name: Build And Test Backend
    runs-on: ubuntu-latest
    needs: [check-is-valid-branch]
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/build-and-test-backend

  deploy-staging:
    name: Build and Deploy Staging
    needs: [build-and-test-backend]
    runs-on: ubuntu-latest
    environment: staging
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: ./.github/actions/build-and-publish-frontend
      with:
        publish-profile: ${{ vars.PUBLISH_PROFILE }}
        publish-angular: ${{ vars.NPM_RUN_COMMAND }}
    - run: echo "Deployed Staging"
  
  selenium-ui-test:
    name: Run Selenium Tests
    needs: [deploy-staging]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: ./.github/actions/selenium-test
    - run: echo "Pass Selenium Tests"
