name: "build and test"

on: 
  push:
    branches:
    - dev
    paths:
    - 'angular/src/**'
    - 'aspnet-core/src/**'
  workflow_dispatch:

jobs:
  check-is-valid-branch:
    name: Check Is Valid Branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/check-is-valid-branch
      with:
        branch_name: dev

  selenium-ui-test:
    name: Run Selenium Tests
    needs: [check-is-valid-branch]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: ./.github/actions/selenium-test
    - run: echo "Pass Selenium Tests"
