name: "Deploy Production"

on: 
  release:
    types: [deleted]
  workflow_run:
    workflows: ["Create Incremental Release Tag"]
    types:
      - completed


jobs:
  deploy-on-release:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - id: latest
        uses: thebritican/fetch-latest-release@v1.0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
        with: 
          ref: ${{ steps.latest.outputs.tag_name }}
      - name: Publish Production
        uses: ./.github/actions/build-and-publish-frontend
        with:
          publish-profile: ${{ vars.PUBLISH_PROFILE }}
          publish-angular: ${{ vars.NPM_RUN_COMMAND }}
      - name: Run Migration
        run: echo "Run Migration"
      - run: echo "Deployed Production"