name: "Create Incremental Release Tag"

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-is-valid-branch:
    name: Check Is Valid Branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/check-is-valid-branch
      with:
        branch_name: main

  release-on-push:
    name: Create Incremental Release Tag
    runs-on: ubuntu-latest
    needs: [check-is-valid-branch]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: norelease