name: "Create Incremental Release Tag"

on: 
  push:
    branches:
      - main

jobs:
  release-on-push:
    name: Create Incremental Release Tag
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: norelease